ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

CREATE USER PROJECT_HYE IDENTIFIED BY kh1234;

GRANT CONNECT, RESOURCE, CREATE VIEW TO PROJECT_HYE;

ALTER USER PROJECT_HYE DEFAULT
TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;