ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

CREATE USER PROJECT_HYE IDENTIFIED BY kh1234;

GRANT CONNECT, RESOURCE, CREATE VIEW TO PROJECT_HYE;

ALTER USER PROJECT_HYE DEFAULT
TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;

---------------------------------------------------------
CREATE TABLE "GRADE"(
	GRADE_NO NUMBER PRIMARY KEY,
	GRADE_NM VARCHAR2(30) NOT NULL
);

COMMENT ON COLUMN "GRADE".GRADE_NO IS '등급 번호';
COMMENT ON COLUMN "GRADE".GRADE_NM IS '등급명';

INSERT INTO "GRADE" VALUES(10,'씨앗');
INSERT INTO "GRADE" VALUES(20,'새싹');
INSERT INTO "GRADE" VALUES(30,'잎새');
INSERT INTO "GRADE" VALUES(40,'가지');
INSERT INTO "GRADE" VALUES(50,'열매');
INSERT INTO "GRADE" VALUES(60,'나무');

CREATE TABLE "MEMBER"(
	MEMBER_NO NUMBER PRIMARY KEY,
	MEMBER_ID VARCHAR2(30) NOT NULL,
	MEMBER_PW VARCHAR2(30) NOT NULL,
	MEMBER_NM VARCHAR2(30) NOT NULL,
	MEMBER_GENDER CHAR(1) CHECK(MEMBER_GENDER IN ('M','F')),
	ENROLL_DATE DATE DEFAULT SYSDATE,
	SECESSION_FL CHAR(1) DEFAULT 'N' CHECK(SECESSION_FL IN ('Y','N')),
	GRADE_NO NUMBER DEFAULT 10 CONSTRAINT MEMBER_GRADE_FK REFERENCES "GRADE" 
);



COMMENT ON COLUMN "MEMBER".MEMBER_NO IS '회원 번호';
COMMENT ON COLUMN "MEMBER".MEMBER_ID IS '회원 아이디';
COMMENT ON COLUMN "MEMBER".MEMBER_PW IS '회원 비밀 번호';
COMMENT ON COLUMN "MEMBER".MEMBER_NM IS '회원 이름';
COMMENT ON COLUMN "MEMBER".MEMBER_GENDER IS '회원 성별';
COMMENT ON COLUMN "MEMBER".ENROLL_DATE IS '회원 가입일';
COMMENT ON COLUMN "MEMBER".SECESSION_FL IS '회원 탈퇴 여부';
COMMENT ON COLUMN "MEMBER".GRADE_NO IS '회원 등급 번호';

















